# Generated by Django 3.2.9 on 2022-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210523_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(max_length=512, null='True', upload_to=''),
        ),
    ]
