# Generated by Django 3.2.9 on 2022-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recureter',
            name='image',
            field=models.FileField(max_length=512, null='True', upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.FileField(max_length=512, null='True', upload_to=''),
        ),
    ]
